//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;

namespace AccesoDatos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gep.com.co/", ConfigurationName="AccesoDatos.AccesoDatosSoap")]
    public interface AccesoDatosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerEsquemaTabla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccesoDatos.TraerEsquemaTablaResponseTraerEsquemaTablaResult> TraerEsquemaTablaAsync(string nombreTabla, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerTabla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataTable> TraerTablaAsync(string nombreTabla, int idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerTablaParametros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccesoDatos.TraerTablaParametrosResponseTraerTablaParametrosResult> TraerTablaParametrosAsync(string tabla, string campos, string condicion, int idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerConsulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccesoDatos.TraerConsultaResponseTraerConsultaResult> TraerConsultaAsync(string consulta, int idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerTablaConArreglo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccesoDatos.TraerTablaConArregloResponseTraerTablaConArregloResult> TraerTablaConArregloAsync(int numeroConsulta, string[] arregloParametros, int aplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/TraerUltimoConsecutivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccesoDatos.TraerUltimoConsecutivoResponseTraerUltimoConsecutivoResult> TraerUltimoConsecutivoAsync(string tabla, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/InsertarTabla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task InsertarTablaAsync(AccesoDatos.InsertarTablaTable table, string nombreTabla, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/InsertarFilaDevuelveConsecutivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> InsertarFilaDevuelveConsecutivoAsync(AccesoDatos.InsertarFilaDevuelveConsecutivoFilaGrabar FilaGrabar, string nombreTabla, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/ActualizarFilas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ActualizarFilasAsync(AccesoDatos.ActualizarFilasTabla tabla, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/EliminarListadeLlaves", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task EliminarListadeLlavesAsync(string NombreTabla, string NombreCampo, string ListadeLLaves, int IdAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gep.com.co/ConnectionDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ConnectionDBAsync(int IdAplicacion);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerEsquemaTablaResponseTraerEsquemaTablaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerTablaResponseTraerTablaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerTablaParametrosResponseTraerTablaParametrosResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerConsultaResponseTraerConsultaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerTablaConArregloResponseTraerTablaConArregloResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class TraerUltimoConsecutivoResponseTraerUltimoConsecutivoResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class InsertarTablaTable
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class InsertarFilaDevuelveConsecutivoFilaGrabar
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gep.com.co/")]
    public partial class ActualizarFilasTabla
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AccesoDatosSoapChannel : AccesoDatos.AccesoDatosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AccesoDatosSoapClient : System.ServiceModel.ClientBase<AccesoDatos.AccesoDatosSoap>, AccesoDatos.AccesoDatosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccesoDatosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AccesoDatosSoapClient.GetBindingForEndpoint(endpointConfiguration), AccesoDatosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccesoDatosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccesoDatosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccesoDatosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccesoDatosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccesoDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.TraerEsquemaTablaResponseTraerEsquemaTablaResult> TraerEsquemaTablaAsync(string nombreTabla, int IdAplicacion)
        {
            return base.Channel.TraerEsquemaTablaAsync(nombreTabla, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task<DataTable> TraerTablaAsync(string nombreTabla, int idAplicacion)
        {
            return base.Channel.TraerTablaAsync(nombreTabla, idAplicacion);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.TraerTablaParametrosResponseTraerTablaParametrosResult> TraerTablaParametrosAsync(string tabla, string campos, string condicion, int idAplicacion)
        {
            return base.Channel.TraerTablaParametrosAsync(tabla, campos, condicion, idAplicacion);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.TraerConsultaResponseTraerConsultaResult> TraerConsultaAsync(string consulta, int idAplicacion)
        {
            return base.Channel.TraerConsultaAsync(consulta, idAplicacion);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.TraerTablaConArregloResponseTraerTablaConArregloResult> TraerTablaConArregloAsync(int numeroConsulta, string[] arregloParametros, int aplicacion)
        {
            return base.Channel.TraerTablaConArregloAsync(numeroConsulta, arregloParametros, aplicacion);
        }
        
        public System.Threading.Tasks.Task<AccesoDatos.TraerUltimoConsecutivoResponseTraerUltimoConsecutivoResult> TraerUltimoConsecutivoAsync(string tabla, int IdAplicacion)
        {
            return base.Channel.TraerUltimoConsecutivoAsync(tabla, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task InsertarTablaAsync(AccesoDatos.InsertarTablaTable table, string nombreTabla, int IdAplicacion)
        {
            return base.Channel.InsertarTablaAsync(table, nombreTabla, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task<string> InsertarFilaDevuelveConsecutivoAsync(AccesoDatos.InsertarFilaDevuelveConsecutivoFilaGrabar FilaGrabar, string nombreTabla, int IdAplicacion)
        {
            return base.Channel.InsertarFilaDevuelveConsecutivoAsync(FilaGrabar, nombreTabla, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarFilasAsync(AccesoDatos.ActualizarFilasTabla tabla, int IdAplicacion)
        {
            return base.Channel.ActualizarFilasAsync(tabla, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task EliminarListadeLlavesAsync(string NombreTabla, string NombreCampo, string ListadeLLaves, int IdAplicacion)
        {
            return base.Channel.EliminarListadeLlavesAsync(NombreTabla, NombreCampo, ListadeLLaves, IdAplicacion);
        }
        
        public System.Threading.Tasks.Task<string> ConnectionDBAsync(int IdAplicacion)
        {
            return base.Channel.ConnectionDBAsync(IdAplicacion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccesoDatosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AccesoDatosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccesoDatosSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.50/AccesoDatos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AccesoDatosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.50/AccesoDatos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AccesoDatosSoap,
            
            AccesoDatosSoap12,
        }
    }
}
